### ISSUE TITLE
fix style select button (Design)

### ISSUE THREAD

**Issue by philipfsr** [matooo3/Pencil2Pixel#45]
The style buttons bottom two edges are sharp and when hovering over the button they become round.

It should be the opposite.

**Comment by matooo3** [comment]
I think this is some bug because of the server, like it was with the icons, because locally i dont have any issues and also on the server version the style of the sliders are not applied.

**Comment by matooo3** [comment]
Did you update the CSS file on the Server?

**Comment by matooo3** [comment]
solved
